---
title: AT 6 - Atomreaktorer
author: Jeppe Møldrup og Mads Damgaard
header-includes:
        \usepackage[utf8]{inputenc}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \chead{Jeppe og Mads}
        \rhead{AT-6}
        \lhead{9/10-2018}
output:
        pdf_document:
            toc: true
---

# Indledning

Størstedelen af mennesker i verden tænker at energikilden i fremtiden skal være grøn og bæredygtig, da fossile brændstoffer
som en ressource løber tør, og ødelægger miljøet. Under grønne og bæredygtige energityper tænker de solenergi, vindenergi,
bølgeenergi og så videre. En af de grønne energityper som har måske en af de største energipotentialer er atomenergi.
Selvom potentialet er der hører man generelt ikke meget om det, og det virker slet ikke til at være oppe til diskussion som
en valgmulighed i Danmark. I denne opgave vil vi se på den udvikling atomenergien har gennemgået, som et alternativ til den
primitive type, der har sået frygt i mange mennesker efter Tjernobyl katastrofen.

# Problemformulering

Hvordan blev atomkraft udviklet som fredelig energiteknologi - og hvad er denne teknologis fremtid?

# Underspørgsmål 1

Gør kort rede for atomkraftværkets udviklingshistorie

## Metode

Til at besvare underspørgsmålet har vi kigget på historiske kilder, der dokumenterer  og beskriver de forskellige kraftværks former, som er blevet brugt, op igennem tiden. Ved udvælgelsen af de kilder vi har brugt til at dokumentere udviklingen af atomkraften har vi brugt kildekritik, for at sikre os at vores kilder er troværdige.

## Delkonklusion

Atomkraft teknologiens udvikling kan splittes op i 4 generationer i forhold til de traditionelle uran kraftværker

Generation 1(1950’erne til 1960’erne)

Herunder det første kommercielle atomkraftværk, Calder Hall, som der blev bygget i Seascape, England i 1956. Calder Hall var af typen AGR(Advanced Gas-Cooled Reactor) hvor man bruger carbondioxid under tryk til at køle reaktoren ned og generere strømmen.

Generation 2(1970’erne til nu)

Denne generation tilhører hovedparten af de nuværende a-værker som er i brug i dag. De er bygget til at have en levetid på omkring 40 år.
Herunder er reaktortypen RBMK(High-power channel reactor) som er systemet der blev brugt i katastrofen i Tjernobyl i 1986. RBMK-reaktorer er den eneste type reaktor i verden der bruger grafit i kontrolstavene og vand som kølemiddel. Og som det viste sig i 1986 var der nogle design valg i RBMK-reaktoren som gjorde den meget farlig. En af disse farlige design valg kommer med at bruge vand som kølevæske, idet vand både er et bedre kølemiddel og et bedre neutron absorberende middel end damp. Det betyder at reaktoren har chance for at “løbe løbsk”. Hvis reaktoren bliver lidt varmere end arbejderne ville have kommer der flere dampbobler i vandet, hvilket vil sige at det nu køler værre og absorberer mindre neutroner, også kaldet positivt feedback.

Generation 3(1990’erne)

Forbedret design med bedre udnyttelse, bedre sikkerhed og længere levetid. Dog har man nu fundet ud af at den øgede udnyttelse medfører mere radioaktivt affald, og dermed er det sværere at opbevare.
Der findes kun nogle få af disse i Japan. Europas første generation 3 værker er under konstruktion i Finland og Frankrig.

Generation 4

Generation 4 er til brug i 2030’erne, og har en række nye teknologier men stadig de samme grundlæggende problemer som de tidligere generationer af uran atomkraftværker, dog bedre end de andre generationer økonomisk og i forhold til radioaktivt affald. De er i øjeblikket ikke en realitet, men blot teori.

# Underspørgsmål 2

Hvilke alternativer inden for fredelig udnyttelse af atomenergi bliver der aktuelt forsket i med henblik på at forhindre  katastrofer (som f. eks. Tjernobyl)?

## Metode

Vi har kigget på naturfagligt empiri, der fortæller om de alternative atomkraftværker, som der bliver forsket i på tidspunktet. Forskere har her udøvet en række eksperimenter, for at finde hvilke stoffer der udsender mest energi ved deres henfald

## Delkonklusion

Der skulle køres et eksperiment i Tjernobyl i 1986 hvor de skulle bringe effekten ned ved omkring 1000 megawatt, men de kom i stedet til at bringe effekten ned på omkring 30 megawatt. Problemet med det er at ved den lave effekt bliver der dannet nogle gasser som er meget neutron absorberende, dvs. at arbejderne nu havde det ret svært med at holde reaktoren i gang. De endte med at få liv i den og bare køre eksperimentet ved omkring 200 megawatt, men for at få den herop blev de nødt til at slå flere forskellige sikkerhedssystemer fra og trække mange kontrolstave næsten helt ud. Og resultatet af dette var at reaktoren så løb løbsk som forklaret i underspørgsmål 1, og blev så varm at der skete flere eksplosioner i reaktoren som sendte en radioaktiv sky op i luften hvor den blev spredt over hele Europa.
I 1985 den 29. marts, blev der vedtaget en beslutning om ikke at inkludere atomenergi i Danmarks fremtidige energiplanlægning, også kaldet beslutningforslag nr. B 103. Beslutningen blev foreslået af S, SF, RV og VS. Denne beslutning sammen med Tjernobyl katastrofen, der skete cirka et år senere, har holdt debatten om atomkraftværker i Danmark, stille.
Men som Rasmus Brygger kommer ind på i sin artikel “Kernekraft fortjener en ny chance” så sker der meget på de 30 år der er gået siden beslutningen om atomenergi i 1985. Lige nu bliver der f.eks. forsket i at bruge grundstoffet thorium i stedet for uran i selve kernen, men selve beslutningen er også baseret på datidens generation 2 reaktorer. Hvor i dag har vi generation 3 og planer for generation 4 reaktorer der er meget mere effektive, sikre og miljøvenlige. Og som Rasmus siger så er vind- og solenergi meget dyrt, mens kulkraftværker ikke er miljøvenlige eller vedvarende. Så Rasmus mener at a-værker tager det bedste fra begge sider, nemlig at det er vedvarende(Det kan holde de næste mange tusind år) og det er miljøvenligt, og at a-værker har fået et unfair dårligt ry fordi der var nogle problemer med tidlige a-værker.

# Underspørgsmål 3

Hvad er fordelene og ulemperne ved en thorium reaktor i forhold til en traditionel uran reaktor?

## Metode

For at undersøge hvad fordelene og ulemperne ved en thorium reaktor i forhold til den traditionelle uran reaktor, har vi fundet naturfaglig empiri omkring begge typer af reaktor. Derefter har vi sammenlignet information omkring begge typer, for at kunne deduktivt konkludere på fordelene og ulemperne ved thorium reaktoren i forhold til den klassiske uran reaktor.

## Delkonklusion

Til fordel for thorium er der estimeret til at være omkring 3-4 gange så meget thorium i forhold til uran. En anden fordel ved thorium er at det er grønnere i den forstand at uran skaber rigtig mange “transuraniske” elementer (kan f.eks. være plutonium), som er den farligste del af det radioaktive affald fra et atomkraftværk. Det tager kun en neutronindfangning til at lave Uran-238 om til et transuranisk element, mens med thorium-232 tager det typisk hele 5 indfangninger før det er muligt. Derfor bliver der produceret væsentligt mindre transuraniske elementer i et thoriumkraftværk, og dermed mindre affald. Derudover kan thorium udnyttes meget mere end uran, i det at næsten alt thorium kan konverteres om til energi, mens det kun er omkring en tohundrededel af uran der kan konverteres til energi. Ydermere kan nogle thorium systemer bruge noget af den radioaktive affald fra U-værker til energiproduktion og i stedet lave affald med meget mindre halveringstider. Thorium kan heller ikke rigtig bruges til at lave atombomber ligesom uran kan, dette kan ses som et stor plus i dag. Under den kolde krig valgte man at bruge uran i stedet for thorium lige præcis fordi de allerede forskede i uran til brug i våben, derfor er der ikke blevet forsket i brug af thorium inden for våben videnskaben, og manglen på info på dette område fremstiller thorium kraftværker som værende mere fredelige.
Der er dog også nogle ulemper ved thorium reaktorer. F.eks bliver der skabt Uran-232 i en thorium reaktor. Uran-232 er en isotop med en meget kort halveringstid, og dens henfaldskæde producere nogle meget energiske gammastråler, som er meget penetrerende, derfor skal man have mere sikkerhed i håndtering og reproduktion af Uran-232 og dens henfald.

# Konklusion

# Perspektivering

# Litteraturliste
