---
header-includes:
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \lhead{Jeppe Møldrup}
        \chead{Fysik aflevering 5}
        \rhead{2/11-2018}
---

# Fysik aflevering 5

## Opgave 1

En pushback-traktor skubber et fly med massen 132 ton med den konstante fart 2.63 m/s.

a. Beregn flyets kinetiske energi, når det skubbes af pushback-traktoren.
   
   Jeg bruger formlen
   $$E_{kin} = \frac{1}{2} m v^2$$
   Så jeg indsætter bare mine værdier
   $$E_{kin} = \frac{1}{2} \cdot 132000 \ kg \cdot (2.63 \ m/s)^2 = 456515.4 \approx 457 \ kJ$$
   Så flyets kinetiske energi når det skubbes af pushback-traktoren er cirka $457$ kJ.

Pushback-traktoren skubber igen et fly med massen 132 ton i vandret retning. Under dette skub er flyet
påvirket af friktionskræfter, som samlet har størrelsen 33.0 kN. I starten af skubbet har flyet en acceleration
med størrelsen 1.62 $m/s^2$.

b. Bestem størrelsen af den kraft, hvormed pushback-traktoren påvirker flyet i starten af skubbet
   
   Formlen for $F_{res}$ med friktion er
   $$F_{res} = F_{fremad} - F_{friktion}$$
   Hvor det er $F_{fremad}$ der er den kraft pushback-traktoren påvirker flyet med. Så jeg isolerer den
   $$F_{fremad} = F_{res} - F_{friktion}$$
   Vi kender ikke $F_{res}$ men hertil bruger jeg formlen
   $$F_{res} = ma$$
   og substituerer det ind i den anden formel
   $$F_{fremad} = ma - F_{friktion}$$
   Så indsætter jeg mine værdier
   $$F_{fremad} = 132000 \ kg \cdot 1.62 \ \frac{m}{s^2} - 33000 \ N = 180840 \ N \approx 181 \ kN$$
   Så størrelsan af den kraft, hvormed pushback-traktoren påvirker flyet i starten af skubbet er cirka 181 kN.
