.ds RH Jeppe Møldrup
    .
.ds CH Matematik 12
.
.ds LH 22/1-2019
.
.ds CF %
.

.EQ
delim $$
.EN

.TL
Matematik Aflevering 12
.AU
Jeppe Møldrup

.SH
9.287*
.LP
En cirkel har centrum i punktet $(0, 0)$ og radius $sqrt 2$. Linjen $l$ har parameterfremstillingen
.EQ
lvec x above y rvec = lvec 3 above -3 rvec + t cdot lvec 1 above -1 rvec, ~~~~t \[in] R
.EN
Opskriv en ligning for cirklen, og bestem koordinatsættet  til hvert af skæringspunkterne mellem linjen $l$ og cirklen.


